codeviewer/urls.py
from django.contrib import admin
from django.urls import path,re_path,reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
app_name='codeviewer'
urlpatterns = [
    path('',views.index,name='index'),
    re_path('^user/(?P<username>[A-Za-z]+)/$',views.userprofile,name='userprofile'),
    re_path('^trending/$',views.trendingsnippet,name='trendingsnippet'),
    re_path('^trending/(?P<language_slug>[\w-]+)/$',views.trendingsnippet,name='trendingsnippet'),
    re_path('^(?P<snippet_slug>[0-9]+)/$',views.snippetdetail,name='snippetdetail'),
    re_path('^tag/(?P<tagname>[\w-]+)/$',views.tagsnippet,name='tagsnippet'),
    re_path('^download/(?P<snippet_slug>[\w-]+)/$',views.download_snippet,name='download_snippet'),
    re_path('^raw/(?P<snippet_slug>[\w-]+)/$',views.raw_snippet,name='raw_snippet'),
    re_path('^contact/$',views.contact,name='contact'),
    #re_path('^login/$',auth_views.LoginView.as_view(template_name='codeviewer/login.html'),name='login'),
    #re_path('^logout/$',auth_views.LogoutView.as_view(template_name='codeviewer/logout.html'),name='logout'),
    re_path('^login/$',views.login,name='login'),
    re_path('^logout/$',views.logout,name='logout'),
    re_path('^user_detail/$',views.user_detail,name='user_detail'),
    re_path('^signup/$',views.signup,name='signup'),
    re_path('^activate/(?P<uidb64>[\w.-]+)/(?P<token>[\w.-]+)/$',views.activate_account,name='activate'),
    re_path('^password-reset/$',auth_views.PasswordResetView.as_view(template_name='codeviewer/password_reset.html',email_template_name='codeviewer/email/password_reset_email.txt',subject_template_name='codeviewer/email/password_reset_subject.txt',success_url=reverse_lazy('codeviewer:password_reset_done')),name='password_reset'),
    re_path('^password-reset-done/$',auth_views.PasswordResetDoneView.as_view(template_name='codeviewer/password_reset_done.html'),name='password_reset_done'),
    re_path('^password-reset-confirm/(?P<uidb64>[\w.-]+)/(?P<token>[\w.-]+)/$',auth_views.PasswordResetConfirmView.as_view(template_name='codeviewer/password_reset_confirm.html',success_url=reverse_lazy('codeviewer:password_reset_complete')),name='password_reset_confirm'),
    re_path('^password-reset-complete/$',auth_views.PasswordResetCompleteView.as_view(template_name='codeviewer/password_reset_complete.html'),name='password_reset_complete'),
    re_path('^password-change/$',auth_views.PasswordChangeView.as_view(template_name='codeviewer/password_change.html',success_url=reverse_lazy('codeviewer:password_change_done')),name='password_change'),
    re_path('^password-change-done/$',auth_views.PasswordChangeDoneView.as_view(template_name='codeviewer/password_change_done.html'),name='password_change_done'),
    re_path('^settings/$',views.settings,name='settings'),
    re_path('^delete/(?P<snippet_slug>[\w-]+)/$',views.delete_snippet,name='delete_snippet'),
    re_path('^search/$',views.search,name='search'),
    #path('add_lang/',views.add_lang,name='add_lang'),
    #re_path('update_lang/(?P<lang_slug>[\w-]+)/',views.update_lang,name='update_lang')
    ]

djangosnippets/urls.py
from django.contrib import admin
from django.urls import path,include
from codeviewer import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('codeviewer.urls',namespace='codeviewer'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

codeviewer/models.py
from django.shortcuts import reverse,render,HttpResponse,get_object_or_404
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from .utils import Preference
from pygments import lexers,highlight
from pygments.formatters import HtmlFormatter
from django.utils.text import slugify
import time

class Language(models.Model):
    name=models.CharField(max_length=100)
    lang_code=models.CharField(max_length=100,unique=True)
    slug=models.SlugField(max_length=100,unique=True)
    mime=models.CharField(max_length=100)
    file_extension=models.CharField(max_length=10)
    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
    def get_lexer(self):
        return lexers.get_lexer_by_name(self.lang_code)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('codeviewer:trendingsnippet',args=[self.slug])
    class Meta:
        ordering=['name']
def get_default_language():
    lang=Language.objects.get_or_create(name='Plain Text',lang_code='text',slug='text',mime='text/plain',file_extension='.txt')
    return lang[0].id
class Author(models.Model):
    user=models.OneToOneField(User,related_name='profile',on_delete=models.CASCADE)
    default_language=models.ForeignKey(Language,on_delete=models.CASCADE,default=get_default_language)
    default_exposure=models.CharField(max_length=10,choices=Preference.exposure_choices,default=Preference.snippet_public)
    default_expiration=models.CharField(max_length=10,choices=Preference.expiration_choices,default=Preference.snippet_expire_never)
    private=models.BooleanField(default=False)
    views=models.IntegerField(default=0)

    def __str__(self):
        return self.user.username
    def get_absolute_url(self):
        return reverse('codeviewer:userprofile',args=[self.user.username])
    def get_snippet_count(self):
        return self.user.snippet_set.count()
    def get_preferences(self):
        return {'language':self.default_language.id,'exposure':self.default_exposure,'expiration':self.default_expiration}
@receiver(post_save,sender=User)
def create_author(sender,**kwargs):
    if kwargs.get('created',False):
        Author.objects.get_or_create(user=kwargs.get('instance'))

class Snippet(models.Model):
    title=models.CharField(max_length=100,blank=True)
    orig_code=models.TextField()
    high_code=models.TextField(help_text='readonly field')
    slug=models.SlugField(max_length=100,unique=True,help_text='readonly field')
    expiration=models.CharField(max_length=10,choices=Preference.expiration_choices)
    exposure=models.CharField(max_length=10,choices=Preference.exposure_choices)
    hits=models.IntegerField(default=0,help_text='readonly field')
    created_on=models.DateTimeField(auto_now_add=True)

    user=models.ForeignKey(User,on_delete=models.CASCADE)
    language=models.ForeignKey(Language,on_delete=models.CASCADE)
    tag=models.ManyToManyField('Tag',blank=True)

    def highlight(self):
        formatter=HtmlFormatter(full=True,linenos=True)
        return highlight(self.orig_code,self.language.get_lexer(),formatter)
    def __str__(self):
        return (self.title if self.title else 'untitled')+'-'+self.language.name
    def get_absolute_url(self):
        return reverse('codeviewer:snippetdetail',args=[self.slug])
    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=str(time.time()).replace('.','')
        self.high_code=self.highlight()
        if not self.title:
            self.title='Untitled'
        super(Snippet,self).save(*args,**kwargs)
    class Meta:
        ordering=['-created_on']
class Tag(models.Model):
    name=models.CharField(max_length=100,unique=True)
    slug=models.CharField(max_length=100,unique=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('codeviewer:tagsnippet',args=[self.slug])

    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        super(Tag,self).save(*args,**kwargs)
    class Meta:
        ordering=['name']

codeviewer/views.py
from django.shortcuts import render,redirect,Http404,get_object_or_404,reverse,get_list_or_404
from django.core.mail import mail_admins
from django.db.models import Q
from django.contrib import auth
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes,force_text
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib import messages
from .decorators import private_snippet
from .forms import *
from .models import *
from .utils import paginate_result
import datetime
# Create your views here.
def userprofile(request,username):
    user=get_object_or_404(User,username=username)
    if user.profile.private and request.user.username!=user.username:
        raise Http404
    elif not user.profile.private and request.user.username!=user.username:
        snippet_list=user.snippet_set.filter(exposure='public')
        user.profile.views+=1
        user.profile.save()
    else:
        snippet_list=user.snippet_set.all()
    snippets=paginate_result(request,snippet_list,5)
    return render(request,'codeviewer/profile.html',{'user':user,'snippets':snippets})
def search(request):
    f = SearchForm(request.GET)
    snippets = []

    if f.is_valid():

        query = f.cleaned_data.get('query')
        mysnippets = f.cleaned_data.get('mysnippet')

        # if mysnippet field is selected, search only logged in user's snippets
        if mysnippets:
            snippet_list = Snippet.objects.filter(
                Q(user=request.user),
                Q(orig_code__icontains=query) | Q(title__icontains=query)
            )

        else:
            qs1 = Snippet.objects.filter(
                Q(exposure='public'),
                Q(orig_code__icontains = query) | Q(title__icontains = query)
                # Q(user=request.user)
            )

            # if the user is logged in then search his snippets
            if request.user.is_authenticated:
               qs2 = Snippet.objects.filter(Q(user=request.user),
                                            Q(orig_code__icontains=query) | Q(title__icontains=query))
               snippet_list = (qs1 | qs2).distinct()

            else:
                snippet_list = qs1

        snippets = paginate_result(request, snippet_list, 5)

    return render(request, 'codeviewer/search.html', {'form': f, 'snippets': snippets })
def tagsnippet(request,tagname):
    t=get_object_or_404(Tag,name=tagname)
    snippet_list=get_list_or_404(t.snippet_set)
    snippets=paginate_result(request,snippet_list,5)
    return render(request,'codeviewer/taglist.html',{'snippets':snippets,'tag':t})
def trendingsnippet(request,language_slug=''):
    lang=None
    snippets=Snippet.objects
    if language_slug:
        snippets=snippets.filter(language__slug=language_slug)
        lang=get_object_or_404(Language,slug=language_slug)
    snippet_list=get_list_or_404(snippets.filter(exposure='public').order_by('-hits'))
    snippets=paginate_result(request,snippet_list,5)
    return render(request,'codeviewer/trending.html',{'snippets':snippets,'lang':lang})
@private_snippet
def snippetdetail(request,snippet_slug):
    snippet=get_object_or_404(Snippet,slug=snippet_slug)
    snippet.hits+=1
    snippet.save()
    return render(request,'codeviewer/snippetdetail.html',{'snippet':snippet})
def index(request):
    if request.method ==  'POST':
        f = SnippetForm(request,request.POST)
        if f.is_valid():
            snippet = f.save(request)
            return redirect(reverse('codeviewer:snippetdetail', args=[snippet.slug]))

    else:
        f = SnippetForm(request)
    return render(request, 'codeviewer/index.html', {'form': f})
@private_snippet
def download_snippet(request,snippet_slug):
    snippet=get_object_or_404(Snippet,slug=snippet_slug)
    file_extension=snippet.language.file_extension
    filename=snippet.slug+file_extension
    res=HttpResponse(snippet.orig_code)
    res['content-disposition']='attachment;filename='+filename+';'
    return res
@private_snippet
def raw_snippet(request,snippet_slug):
    snippet=get_object_or_404(Snippet,slug=snippet_slug)
    return HttpResponse(snippet.orig_code,content_type=snippet.language.mime)
def contact(request):
    if request.method == 'POST':
        f = ContactForm(request,request.POST)
        if f.is_valid():

            if request.user.is_authenticated:
                name = request.user.username
                email = request.user.email
            else:
                name = f.cleaned_data['name']
                email = f.cleaned_data['email']
            subject = "You have a new Feedback from {}:<{}>".format(name,email)
            message="Purpose:{}\n\nDate:{}\n\nMessage:\n\n{}".format(dict(f.purpose_choices).get(f.cleaned_data['purpose']),datetime.datetime.now(),f.cleaned_data['message'])
            mail_admins(subject,message)
            messages.add_message(request,messages.INFO,'Thanks for submitting your feedback.')
            return redirect('codeviewer:contact')
    else:
        f=ContactForm(request)
    return render(request,'codeviewer/contact.html',{'form':f})
def login(request):
    if request.user.is_authenticated:
        return redirect('codeviewer:userprofile',username=request.user.username,email=request.user.email)
    if request.POST:
        f=LoginForm(request.POST)
        if f.is_valid():
            user=User.objects.filter(email=f.cleaned_data['email'])
            if user:
                username=user[0].username
                password=f.cleaned_data['password']
                user=auth.authenticate(username=username,password=password)
                if user:
                    auth.login(request,user)
                    return redirect(request.GET.get('next')or 'codeviewer:index')
            messages.add_message(request,messages.INFO,'Invalid email/password.')
            return redirect('codeviewer:login')
    else:
        f=LoginForm()
    return render(request,'codeviewer/login.html',{'form':f})
@login_required
def logout(request):
    auth.logout(request)
    return render(request,'codeviewer/logout.html')
@login_required
def user_detail(request):
    user=get_object_or_404(User,id=request.user.id)
    return render(request,'codeviewer/user_detail.html',{'user':user})
def signup(request):
    if request.user.is_authenticated:
        return redirect('codeviewer:userprofile',username=request.user.username,email=request.user.email)
    if request.POST:
        f=CreateUserForm(request.POST)
        if f.is_valid():
            f.save(request)
            messages.success(request,'Account created successfully.check your mail section to verify your account.')
            return redirect('codeviewer:signup')
    else:
        f=CreateUserForm()
    return render(request,'codeviewer/signup.html',{'form':f})
def activate_account(request,uidb64,token):
    try:
        uid=force_text(urlsafe_base64_decode(uidb64))
        user=User.objects.get(pk=uid)
    except(TypeError,ValueError,OverflowError,User.DoesNotExist):
        user=None
    if user is not None and default_token_generator.check_token(user,token):
        user.is_active=True
        user.save()
        messages.add_message(request,messages.INFO,'Account activated.Please login.')
    else:
        messages.add_message(request,messages.INFO,'Link expired.Contact admin to login.')
    return redirect('codeviewer:login')
@login_required
def settings(request):
    user=get_object_or_404(User,id=request.user.id)
    if request.POST:
        f=SettingForm(request.POST,instance=user.profile)
        if f.is_valid():
            f.save()
            messages.add_message(request,messages.INFO,'Settings updated.')
            return redirect('codeviewer:settings')
    else:
        f=SettingForm(instance=user.profile)
    return render(request,'codeviewer/settings.html',{'form':f})
@login_required
def delete_snippet(request,snippet_slug):
    snippet=get_object_or_404(Snippet,slug=snippet_slug)
    if request.user!=snippet.user:
        raise Http404
    snippet.delete()
    return redirect('codeviewer:userprofile',request.user)
#def add_lang(request):
#    if request.POST:
#        f=LanguageForm(request.POST)
#        if f.is_valid():
#            lang=f.save()
#            messages.add_message(request,messages.INFO,'New language saved.')
#            return redirect('codeviewer:add_lang')
#    else:
#        f=LanguageForm()
#    return render(request,'codeviewer/add_lang.html',{'form':f})
#def update_lang(request,lang_slug):
#    l=get_object_or_404(Language,slug__iexact=lang_slug)
#    if request.POST:
#        f=LanguageForm(request.POST,instance=l)
#        if f.is_valid():
#            lang=f.save()
#            messages.add_message(request,messages.INFO,'Language updated.')
#            return redirect('codeviewer:update_lang',lang.slug)
#    else:
#        f=LanguageForm(instance=l)
#    return render(request,'codeviewer/update_lang.html',{'form':f})

codeviewer/templates/codeviewer/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
    {% load humanize %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}CodeViewer{% endblock %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'codeviewer/css/bootstrap.min.css' %}" >

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'codeviewer/css/bootstrap-select.min.css' %}" >

    <link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="{% static 'codeviewer/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'codeviewer/css/default.css' %}">
</head>
<body>

<nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'codeviewer:index' %}">CodeViewer</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li {% if request.path == '/' %}class='active'{% endif %} >
                    <a href="{% url 'codeviewer:index' %}">Add new</a>
                </li>
                <li {% if request.path == '/trending/' %}class='active'{% endif %}>
                    <a href="{%url 'codeviewer:trendingsnippet' %}">Trending<span class="sr-only">(current)</span></a>
                </li>
                <li {% if request.path == '/about/' %}class='active'{% endif %}>
                    <a href="">About</a>
                </li>
                <li {% if request.path == '/contact/' %}class='active'{% endif %}>
                    <a href="{%url 'codeviewer:contact' %}">Contact</a>
                </li>
            </ul>

            <form action="{% url 'codeviewer:search' %}" class="navbar-form navbar-left" method="get">
                <div class="form-group">
                    <input type="text" name="query" class="form-control" placeholder="Search" value="{{request.GET.query}}">
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true" aria-expanded="false">
                        {% if request.user.is_authenticated %}
                            {{ request.user.username|upper }}
                        {% else %}
                            GUEST
                        {% endif %}
                        <span class="caret"></span>
                    </a>
                    {% if request.user.is_authenticated %}
                        <ul class="dropdown-menu">
                            <li><a href="{%url 'codeviewer:userprofile' request.user %}">My Pastes</a></li>
                            <li><a href="{% url 'codeviewer:user_detail' %}">Account Details</a></li>
                            <li><a href="{%url 'codeviewer:settings' %}">Settings</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'codeviewer:logout' %}">Logout</a></li>
                        </ul>
                    {% else %}
                        <ul class="dropdown-menu">
                            <li><a href="{%url 'codeviewer:signup' %}">Sign Up</a></li>
                            <li><a href="{% url 'codeviewer:login' %}">Login</a></li>
                        </ul>
                    {% endif %}
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>


<div class="container">

    <div class="row">

        <div class="col-lg-9 col-md-9">

            {% if not request.user.is_authenticated and not request.path == '/login/'  %}
                <p class="alert alert-info">
                    <a href="{% url 'codeviewer:login' %}?next={{request.path}}" class="alert-link">Login</a> to access other cool features.
                </p>
            {% endif %}


            {% block main %}
                {#  override this block in the child template  #}
            {% endblock %}

        </div>

        <div class="col-lg-3 col-md-3 text-center hidden-sm hidden-xs">
            <p>Recent Snippets</p>

            <div class="list-group">
              {% for recent in recent_snippet %}

                <a href="{{ recent.get_absolute_url }}" class="list-group-item">
                    <h5 class="list-group-item-heading"><span class="fas fa-globe"
                        "></span> {{ recent.title }}</h5>
                    <p class="list-group-item-text">{{ recent.created_on|naturaltime }}</p>
                </a>
                {% endfor %}
                </div>
          </div>
    </div>
</div>

<hr>

<footer>
    <div class="social-icons">
        <div class="container text-center">
            <ul class="list-inline">
                <li class="list-inline-item social-github">
                    <a href="https://github.com/">
                        <i class="fab fa-github"></i>
                    </a>
                </li>
                <li class="list-inline-item social-twitter">
                    <a href="https://twitter.com/">
                        <i class="fab fa-twitter-square"></i>
                    </a>
                </li>
                <li class="list-inline-item social-facebook">
                    <a href="https://www.facebook.com/">
                        <i class="fab fa-facebook-square"></i>
                    </a>
                </li>
                <li class="list-inline-item social-google-plus">
                    <a href="https://plus.google.com/">
                        <i class="fab fa-google-plus-g"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-footer">
        <div class="container text-center">
            <ul>
                <li><a href="#">Source Code</a></li>
                <li><a href="#">OverIQ</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">Other Tutorials</a></li>
            </ul>
        </div>
    </div>
</footer>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src={% static "codeviewer/js/jquery.js" %}></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<!-- Latest compiled and minified JavaScript -->
<script src={% static "codeviewer/js/bootstrap.min.js" %}></script>

<!-- Latest compiled and minified JavaScript -->
<script src={% static "codeviewer/js/bootstrap-select.min.js" %}></script>

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })

</script>

</body>
</html>

codeviewer/templates/codeviewer/password_reset_complete.html
{% extends 'codeviewer/base.html' %}

{% load static %}
{% load humanize %}

{% block main %}

    <div class="row">

        <div class="col-lg-6 col-md-6 col-sm-6">

            <h4>Password Reset Success</h4>

            <hr>

            <div class="db-form">

                <p>Your password has been reset. Click <a href="{% url  'codeviewer:login' %}">here</a> to login.</p>

            </div>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">
            <h4>Related Links</h4>
            <p>
                <a href="{%url 'codeviewer:password_reset' %}">Forgot Password?</a> <br>
                <a href="{% url 'codeviewer:signup' %}">Sign Up.</a>
                <a href="#">Feedback</a>
            </p>
        </div>

    </div>

{% endblock %}

codeviewer/templates/codeviewer/snippetdetail.html
{% extends 'codeviewer/base.html' %}

{% load static %}

{% block main %}

    <div class="media post-meta">
        <div class="media-left">
            <a href="#">
                <img alt="64x64" class="media-object" data-src="holder.js/64x64" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PCEtLQpTb3VyY2UgVVJMOiBob2xkZXIuanMvNjR4NjQKQ3JlYXRlZCB3aXRoIEhvbGRlci5qcyAyLjYuMC4KTGVhcm4gbW9yZSBhdCBodHRwOi8vaG9sZGVyanMuY29tCihjKSAyMDEyLTIwMTUgSXZhbiBNYWxvcGluc2t5IC0gaHR0cDovL2ltc2t5LmNvCi0tPjxkZWZzPjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+PCFbQ0RBVEFbI2hvbGRlcl8xNjFkYzE3YWQ0ZiB0ZXh0IHsgZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQgfSBdXT48L3N0eWxlPjwvZGVmcz48ZyBpZD0iaG9sZGVyXzE2MWRjMTdhZDRmIj48cmVjdCB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIGZpbGw9IiNFRUVFRUUiLz48Zz48dGV4dCB4PSIxMi4xNzk2ODc1IiB5PSIzNi41Ij42NHg2NDwvdGV4dD48L2c+PC9nPjwvc3ZnPg==" data-holder-rendered="true" style="width: 64px; height: 64px;">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">{{ snippet.title|default:"Untitled" }}</h4>
            <p>
                <i class="fas fa-user" data-toggle="tooltip" title="" data-original-title="Paste creator"></i> by
                {{ snippet.user.username|capfirst }} &nbsp;
                <i class="fas fa-calendar-alt" data-toggle="tooltip" title="" data-original-title="Creation Date" ></i>
                <time title="{{ snippet.created_on }}">{{ snippet.created_on|date:"M jS,  Y" }}</time> &nbsp;</span>
                <i class="fas fa-eye"  data-toggle="tooltip" title="" data-original-title="Visits to this paste" ></i>
                {{ snippet.hits }} &nbsp;&nbsp;
                <i class="fas fa-stopwatch" data-toggle="tooltip" title="" data-original-title="Expiration time"></i>
                {{ snippet.expiration }}  &nbsp;
                {% if snippet.tag.all %}
                    <i class="fas fa-tags" data-toggle="tooltip" title="" data-original-title="Tags"></i>
                    {% for tags in snippet.tag.all %}
                        <a href="{{ tags.get_absolute_url}}">{{ tags }}</a>{% if not forloop.last %},{% endif %}
                    {% endfor %}
                {% endif %}
            </p>
        </div>

    </div>

    <div class="codeblock">
        <div class="toolbar clearfix">
            <span class="at-left"><a href="{% url 'codeviewer:trendingsnippet' snippet.language.slug %}">{{ snippet.language }}</a></span>
            <span class="at-right">
              {% if snippet.user == request.user %}
                <a onclick="return confirm('Sure you want to delete this paste? ')" href="{% url 'codeviewer:delete_snippet' snippet.slug %}">delete</a>
              {% endif %}
                <a href="{% url 'codeviewer:raw_snippet' snippet.slug %}">raw</a>
                <a href="{% url 'codeviewer:download_snippet' snippet.slug %}">download</a>
            </span>
        </div>
        <div class="code-wrapper">{{ snippet.high_code|safe }}</div>
    </div>

{% endblock %}